### ISSUE TITLE
Issue Demo KVK credentials

### ISSUE THREAD

**Issue by TJGeelen** [privacybydesign/irma-demo-schememanager#120]
@michielmayer I believe this is relevant for you.

When issuing demo credentials via the organisatiegegevens.signicat.dev there are 2 problems:
- When trying to issue KVK credentials with an empty demo persoonsgegevens there is an infinite loop in step 2 of the KVK. See screenprints; ![IMG_7004](https://github.com/privacybydesign/irma-demo-schememanager/assets/150123208/43dd45fb-c01c-4dc0-bb70-e0b0112bd119)
![IMG_7007](https://github.com/privacybydesign/irma-demo-schememanager/assets/150123208/2a60e90e-2009-4589-a42e-238b8406b1ca)
![IMG_7005](https://github.com/privacybydesign/irma-demo-schememanager/assets/150123208/c8ac8852-7edc-47da-94da-42c8dadfb67e)
- When trying to issue KVK credentials with a random populated demo persoonsgegevens you get to step 3 'vind je bedrijf'  where you can search on KVK nummer or handelsnaam. No entry gives any results and you are therefore unable to proceed.
![image0](https://github.com/privacybydesign/irma-demo-schememanager/assets/150123208/fc5acf2c-4198-4939-b395-bea4608f9b17)

**Comment by ivard** [comment]
This seems like a problem with the kvk issuer and not with the demo scheme configuration. Or do you have specific improvements in mind for the scheme configuration?

**Comment by TJGeelen** [comment]
With this issue you are unable to use the demo scheme, however the problem is on the KVK side (hence the tag of Michiel). Do you want me to move this issue? and whereto?

**Comment by michielmayer** [comment]
This is an issue with the issuer indeed. I will look into the first issue. That is a bug. Thanks! The second one happens due to the fact that your on the dev environment. Try to search for 'wit', and you will find organisations. For a better experience use the following personal data: 
First names - Voornamen: Jan
Full Name - Volledige naam: Jan Klaasen
Surname - Achternaam: Klaasen
Date Of Birth - Geboortedatum: 01-01-2000 (exactly this format)

**Comment by ivard** [comment]
Okay, nice that you found the issue. I'll close this issue then.
